{{- if not .Values.vaultwarden.adminToken.existingSecret }}  
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "vaultwarden.fullname" . }}-admin-token
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
data:
  ADMIN_TOKEN: {{ .Values.vaultwarden.adminToken.value | b64enc | quote }}
{{- end }}

{{- if not .Values.vaultwarden.database.existingSecret }}  
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "vaultwarden.fullname" . }}-db-creds
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ .Values.vaultwarden.database.connectionString | b64enc | quote }}
{{- end }}

{{- if not .Values.vaultwarden.smtp.password.existingSecret  }}  
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "vaultwarden.fullname" . }}-smtp
  labels:
    {{- include "vaultwarden.labels" . | nindent 4 }}
data:
  SMTP_PASSWORD: {{ .Values.vaultwarden.smtp.password.value | b64enc | quote }}
{{- end }}
